name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.100

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build .NET MAUI App
      run: dotnet build -c Release

    - name: Create Temporary Folders
      run: mkdir -p $GITHUB_WORKSPACE/temp/msix $GITHUB_WORKSPACE/temp/dmg

    - name: Create MSIX Package
      run: dotnet msbuild -t:Publish -p:Configuration=Release /p:OutputPath=$GITHUB_WORKSPACE/temp/msix

    - name: Create DMG Package
      run: |
        # Add commands to create DMG package here
        # Example: hdiutil create -format UDRW -srcfolder $GITHUB_WORKSPACE/temp/dmg -ov $GITHUB_WORKSPACE/temp/dmg/output.dmg

    - name: Archive MSIX Package
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        mv $GITHUB_WORKSPACE/temp/msix/*.msix $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder.msix

    - name: Archive DMG Package
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        mv $GITHUB_WORKSPACE/temp/dmg/*.dmg $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder.dmg

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload MSIX Package
      id: upload-msix
      uses: actions/upload-artifact@v2
      with:
        name: msix-package
        path: $GITHUB_WORKSPACE/artifacts/*.msix

    - name: Upload DMG Package
      id: upload-dmg
      uses: actions/upload-artifact@v2
      with:
        name: dmg-package
        path: $GITHUB_WORKSPACE/artifacts/*.dmg

    - name: Add MSIX Package to Release
      uses: actions/upload-release-asset@v1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder.msix
        asset_name: GreenDragonTranscoder.msix
        asset_content_type: application/octet-stream

    - name: Add DMG Package to Release
      uses: actions/upload-release-asset@v1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder.dmg
        asset_name: GreenDragonTranscoder.dmg
        asset_content_type: application/octet-stream
