name: MacOS - Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.101

      - name: Setup xCode latest
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install .NET MAUI workload for macOS
        run: dotnet workload install maui-maccatalyst

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build .NET MAUI App
        run: dotnet build -c Release -t:Build -p:TargetFramework=net8.0-maccatalyst -p:Arch=${{ matrix.arch }}

      - name: Create Temporary Folder for DMG
        run: mkdir -p $GITHUB_WORKSPACE/temp/dmg-${{ matrix.arch }}

      - name: Create DMG Package
        run: |
          ls -l /Users/runner/work/GreenDragonTranscoder/GreenDragonTranscoder/GreenDragonTranscoder.Hybrid/bin/Release/net8.0-maccatalyst/maccatalyst-${{ matrix.arch }}
          hdiutil create -format UDRW -srcfolder /Users/runner/work/GreenDragonTranscoder/GreenDragonTranscoder/GreenDragonTranscoder.Hybrid/bin/Release/net8.0-maccatalyst/maccatalyst-${{ matrix.arch }} -ov $GITHUB_WORKSPACE/temp/dmg-${{ matrix.arch }}/output.dmg

      - name: Convert DMG to Read-only
        run: hdiutil convert $GITHUB_WORKSPACE/temp/dmg-${{ matrix.arch }}/output.dmg -format UDZO -o $GITHUB_WORKSPACE/temp/dmg-${{ matrix.arch }}/output-read-only.dmg

      - name: Archive DMG Package
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          mv $GITHUB_WORKSPACE/temp/dmg-${{ matrix.arch }}/output-read-only.dmg $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-${{ matrix.arch }}.dmg

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release 1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload DMG Package
        id: upload-dmg
        uses: actions/upload-artifact@v2
        with:
          name: dmg-package
          path: $GITHUB_WORKSPACE/artifacts/*.dmg
