name: MacOS - Build and Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.101

    - name: Setup xCode latest
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Install .NET MAUI workload for macOS
      run: dotnet workload install maui-maccatalyst  
  
    - name: Restore Dependencies
      run: dotnet restore

    - name: Create Artifacts Folder
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        
    # Build .NET MAUI App for macOS (maccatalyst-x64)
    - name: Build .NET MAUI App for macOS (maccatalyst-x64)
      run: dotnet build -c Release -t:Build -p:TargetFramework=net8.0-maccatalyst -p:Arch=x64

    # Create DMG Package for maccatalyst-x64
    - name: Create DMG Package (maccatalyst-x64)
      run: |
        ls -l /Users/runner/work/GreenDragonTranscoder/GreenDragonTranscoder/GreenDragonTranscoder.Hybrid/bin/Release/net8.0-maccatalyst/maccatalyst-x64
        hdiutil create -format UDRW -srcfolder /Users/runner/work/GreenDragonTranscoder/GreenDragonTranscoder/GreenDragonTranscoder.Hybrid/bin/Release/net8.0-maccatalyst/maccatalyst-x64 -ov $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-x64.dmg

    - name: Debug - List Artifacts Directory
      run: |
        ls -l $GITHUB_WORKSPACE/artifacts

    - name: Convert DMG to Read-only (maccatalyst-x64)
      run: hdiutil convert $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-x64.dmg -format UDZO -o $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-x64-read-only.dmg

    - name: Debug - List Artifacts Directory
      run: |
        ls -l $GITHUB_WORKSPACE/artifacts

    # Build .NET MAUI App for macOS (maccatalyst-arm64)
    - name: Build .NET MAUI App for macOS (maccatalyst-arm64)
      run: dotnet build -c Release -t:Build -p:TargetFramework=net8.0-maccatalyst -p:Arch=arm64

    # Create DMG Package for maccatalyst-arm64
    - name: Create DMG Package (maccatalyst-arm64)
      run: |
        ls -l /Users/runner/work/GreenDragonTranscoder/GreenDragonTranscoder/GreenDragonTranscoder.Hybrid/bin/Release/net8.0-maccatalyst/maccatalyst-arm64
        hdiutil create -format UDRW -srcfolder /Users/runner/work/GreenDragonTranscoder/GreenDragonTranscoder/GreenDragonTranscoder.Hybrid/bin/Release/net8.0-maccatalyst/maccatalyst-arm64 -ov $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-arm64.dmg

    - name: Debug - List Artifacts Directory
      run: |
        ls -l $GITHUB_WORKSPACE/artifacts

    - name: Convert DMG to Read-only (maccatalyst-arm64)
      run: hdiutil convert $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-arm64.dmg -format UDZO -o $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-arm64-read-only.dmg

    - name: Debug - List Artifacts Directory
      run: |
        ls -l $GITHUB_WORKSPACE/artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Debug - List Artifacts Directory
      run: |
        ls -l $GITHUB_WORKSPACE/artifacts

    - name: Upload DMG Package x64
      id: upload-release-asset-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-x64-read-only.dmg
        asset_name: GreenDragonTranscoder-x64.dmg
        asset_content_type: application/octet-stream

    - name: Upload DMG Package arm64
      id: upload-release-asset-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/artifacts/GreenDragonTranscoder-arm64-read-only.dmg
        asset_name: GreenDragonTranscoder-arm64.dmg
        asset_content_type: application/octet-stream
